[package]
name = "rydes-api"
version = "0.1.0"
authors = ["Ibrahim Alhamad <hi@ialhamad.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
