version: "3"
services:
  api:
    image: rydes-api:v.0.0.6
    ports:
      - "3001:3000"
    entrypoint: ["brydes-api"]
    expose:
      - 3000
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URI: "postgresql://zlatan:yeetus@rydes:5432"
  db:
    image: postgres:12
    mem_limit: 1536MB
    mem_reservation: 1G
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_USER: zlatan
      POSTGRES_PASSWORD: yeetus
    ports:
      - "5432:5432"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
 
volumes:
  db-data:
